image: python:3.10

stages:
  - tests
  - compress

Static Analyzer:
  stage: tests
  script:
    - pip install black
    - black --check --diff .
  allow_failure: true

Tests:
  stage: tests
  script:
    - pip install -r service/requirements.txt
    - coverage run --concurrency=greenlet --source=service/app -m pytest service/tests
    - coverage report
    - coverage xml
  coverage: '/TOTAL.*\s+(\d+\%)/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: 'coverage.xml'

compress:
  stage: compress
  image: alpine
  before_script:
    - apk add --update zip
  script:
    - zip -r service.zip
        service/app 
        service/data
        service/nginx 
        service/docker-compose.yml
        service/Dockerfile
        service/requirements.txt
    - zip -r checker.zip checker
  artifacts:
    paths:
      - service.zip
      - checker.zip
    when: on_success
